//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// MFCApplication5.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFCAPPLICATION5_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDB_CHESSE                      130
#define IDB_CHICKEN                     131
#define IDB_FORK                        133
#define IDB_SHRIMP                      134
#define IDB_SQUID                       135
#define IDB_COFFEE                      136
#define IDB_CIDER                       137
#define IDB_COKE                        138
#define IDB_MILKSHAKE                   139
#define IDB_ORANGE                      140
#define IDB_TANSAN                      141
#define IDB_ZEROCIDER                   142
#define IDB_ZEROCOKE                    143
#define IDB_FRENCH_FRIES                146
#define IDB_CHEESEBALL                  147
#define IDB_NUGGET                      148
#define IDB_COLESLAW                    149
#define IDB_CORN_SALAD                  150
#define IDB_CHEESE_STICK                151
#define IDB_SOFTCON                     152
#define IDB_CHOCOCON                    153
#define IDB_WAFFLE                      154
#define IDB_CHURROS                     155
#define IDB_INSHOP                      156
#define IDB_TAKEOUT                     157
#define IDB_BUGER                       158
#define IDB_DRINK                       159
#define IDB_DESSERT                     160
#define IDB_SIDE                        161
#define IDB_PAY                         162
#define IDB_BACK                        164
#define IDB_POINT                       165
#define IDB_CARD                        166
#define IDB_TEXT2                       167
#define IDB_COUPON                      168
#define IDB_TEXT1                       169
#define IDB_CASH                        170
#define IDB_NO                          172
#define IDD_DIALOG1                     175
#define IDB_BUL_BURGER                  177
#define IDB_SET                         178
#define IDB_SOLO                        179
#define IDB_SHIRIMP_BURGER              182
#define IDD_DIALOG2                     183
#define IDD_DIALOG3                     184
#define IDB_CHEESE_BURGER               185
#define IDD_DIALOG4                     185
#define IDD_DIALOG5                     186
#define IDB_CHICKEN_BURGER              187
#define IDD_DIALOG6                     187
#define IDB_SQUID_BURGER                188
#define IDB_DOUBLE_BURGER               189
#define IDB_BEAF                        190
#define IDC_BUGER                       1000
#define IDC_DRINK                       1001
#define IDC_SIDE                        1002
#define IDC_DESSERT                     1003
#define IDC_CHESSE                      1004
#define IDC_CHEESSE                     1004
#define IDC_BEAF                        1005
#define IDC_SQUID                       1006
#define IDC_FORK                        1007
#define IDC_SHRIMP                      1008
#define IDC_CHICKEN                     1009
#define IDC_COKE                        1010
#define IDC_CIDER                       1011
#define IDC_ZEROCOKE                    1012
#define IDC_ZEROCIDER                   1013
#define IDC_MILKSHAKE                   1014
#define IDC_COFFEE                      1015
#define IDC_FRENCH_FRIES                1016
#define IDC_CHEESEBALL                  1017
#define IDC_NUGGET                      1018
#define IDC_COLESLAW                    1019
#define IDC_CORN_SALAD                  1020
#define IDC_CHEESE_STICK                1021
#define IDC_SOFTCON                     1022
#define IDC_WAFFLE                      1023
#define IDC_CHURROS                     1024
#define IDC_CHOCOCON                    1025
#define IDC_LIST                        1027
#define IDC_PAY                         1028
#define IDC_INSHOP                      1029
#define IDC_TAKEOUT                     1030
#define IDC_BACK                        1032
#define IDC_CARD                        1033
#define IDC_COUPON                      1035
#define IDC_CASH                        1036
#define IDC_POINT                       1037
#define IDC_TEXT1                       1038
#define IDC_TEXT2                       1039
#define IDC_NO                          1040
#define IDC_SET                         1042
#define IDC_SOLO                        1043
#define IDC_BUL_BURGER                  1044
#define IDC_SHIRIMP_BURGER              1046
#define IDC_CHICKEN_BURGER              1047
#define IDC_CHEESE_BURGER               1048
#define IDC_DOUBLE_BURGER               1049
#define IDC_SQUID_BURGER                1050

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        191
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
